### ISSUE TITLE
'test_objectt' object has no attribute 'eval_batch'

### ISSUE THREAD

**Issue by Darylnn** [TrustAI/DeepConcolic#16]
Thank you for providing this open source attack for the community. I tried to replicate your attack but was unable to do so, could you help me troubleshoot this?

I tried running the MNIST model as per the instructions in the readme.
`python` deepconcolic.py --model ../saved_models/mnist_complicated.h5 --mnist-data --outputs outs/`

 But unfortunately, I had this error.
![25888fcc-2f4d-47f4-8258-f93b7a649abb](https://user-images.githubusercontent.com/61144786/92593966-9c731e00-f2d4-11ea-8415-0cd6e5200672.jpg)

Do you know how I can mitigate this error? Would really appreciate your help in this!

**Comment by nberth** [comment]
Hi @Wrathar ,

Indeed that's a genuine bug related with features that are probably just not exercised on a regular basis. I've just submitted a pull request that should fix this. It should be in master soon I guess.

**Comment by Darylnn** [comment]
Thank you for the prompt response, I will pull and try it again
