### ISSUE TITLE
Neuron Boundary Coverage not supported

### ISSUE THREAD

**Issue by ForeverZyh** [TrustAI/DeepConcolic#3]
Hello, the criterion argument has 'bc' in README as well as in the paper, but in implementation, the NBC is not supported.

**Comment by theyoucheng** [comment]
Hi ForeverZyh,

A preliminary implementation of NBC for MNIST and CIFAR-10 can be found as follows

https://github.com/TrustAI/DeepConcolic/blob/master/ASE-experiments/L0%20norm/CIFAR10/CIFAR10_bc.py
https://github.com/TrustAI/DeepConcolic/blob/master/ASE-experiments/L0%20norm/MNIST/MNIST_bc.py
https://github.com/TrustAI/DeepConcolic/blob/master/ASE-experiments/L-infinity%20norm/CIFAR10/CIFAR10_bc.py
https://github.com/TrustAI/DeepConcolic/blob/master/ASE-experiments/L-infinity%20norm/MNIST/MNIST_bc.py

A full-fledged support still needs to be added.

With best regards,
Youcheng

**Comment by ForeverZyh** [comment]
Thanks!
