### ISSUE TITLE
Why use a BUFFER_SIZE constant in the function update_nc_map_via_inst?

### ISSUE THREAD

**Issue by lingjunz** [TrustAI/DeepConcolic#6]
Hello, I have some questions when review the  _update_nc_map_via_inst_ function in utils.py.
 I'm not quite sure the purpose of constant _BUFFER_SIZE_ . 

In my opinion, each element in _clayers[i].activations_  represents an activation pattern produced by an instance. So when we update nc_map via current instance, why should we have operations on current nc_map and previous activation pattern? 

Thanks a lot for your kindly assistance.
```
def update_nc_map_via_inst(clayers, activations, layer_feature=None):
  for i in range(0, len(clayers)):
    ## to get the act of layer 'i'
    act=copy.copy(activations[clayers[i].layer_index])
    ## TODO
    if act_in_the_layer(clayers[i].layer)=='relu':
      act[act==0]=MIN/10
    act[act>=0]=0
    if clayers[i].nc_map is None: ## not initialized yet
      clayers[i].initialize_nc_map(layer_feature)
      clayers[i].nc_map=np.logical_and(clayers[i].nc_map, act)
    else:
      clayers[i].nc_map=np.logical_and(clayers[i].nc_map, act)
    ## update activations after nc_map change
    if len(clayers[i].activations)>=BUFFER_SIZE:
      ind=np.random.randint(0,BUFFER_SIZE)
      clayers[i].activations[ind]=(act)
    else:
      clayers[i].activations.append(act)
    ## clayers[i].update_activations()
    for j in range(0, len(clayers[i].activations)):
      clayers[i].activations[j]=np.multiply(clayers[i].activations[j], clayers[i].nc_map)
      clayers[i].activations[j][clayers[i].activations[j]>=0]=MIN
```

**Comment by theyoucheng** [comment]
Existing activation patterns are regarded as very useful information for understanding the internal status of the neural network under test. The very first idea is to keep the activation pattern of every test input: every time a new test input is obtained, its 'activation pattern'  is inserted into 'clayers[i].activations'. In the end, for efficiency, 'BUFFER_SIZE' has to be used to control the maximum size of the vector 'clayers[i].activations'.
