### ISSUE TITLE
Is batch normalization layer supported?

### ISSUE THREAD

**Issue by zxydi1992** [TrustAI/DeepConcolic#7]
Hello, 

Thank you for the awesome package. I found it seems that the library does not support a batch normalization layer in a model. Since the batch normalization is quite useful, is there any future plans for supporting it?

**Comment by theyoucheng** [comment]
Hello,

Thank you for your message. I agree that it would be useful to support the batch normalisation layer (and a few others). Unfortunately, at present we do not have enough people to allocate for this task.

Best regards,
Youcheng
